version: '3.4' 

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
          - 8000:8000
        volumes:
          -  ./backend/app:/backend/app
        command: uvicorn app.backend_server:app --reload --host 0.0.0.0 --port 8000
        networks:
          - localnetwork


networks:
  localnetwork:
    external: true
